# Generated by Django 5.2.2 on 2025-06-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=20, verbose_name='Nombre COrto')),
                ('anulate', models.BooleanField(default=True, verbose_name='Anulado')),
            ],
        ),
    ]
