# Generated by Django 5.2.2 on 2025-06-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departamento", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamento",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nombre"
            ),
        ),
        migrations.AlterField(
            model_name="departamento",
            name="surname",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Nombre Corto"
            ),
        ),
    ]
