# Generated by Django 5.2.2 on 2025-06-12 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departamento", "0002_alter_departamento_name_alter_departamento_surname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firts_name",
                    models.CharField(max_length=100, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                (
                    "job",
                    models.CharField(
                        choices=[
                            ("0", "Gerente"),
                            ("1", "Desarrollador"),
                            ("2", "Diseñador"),
                            ("3", "Analista"),
                            ("4", "Otro"),
                        ],
                        default="4",
                        max_length=1,
                        verbose_name="Trabajo",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departamento.departamento",
                    ),
                ),
            ],
        ),
    ]
