# Generated by Django 5.2.2 on 2025-06-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prueba",
            name="subtitulo",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="prueba",
            name="titulo",
            field=models.CharField(max_length=30),
        ),
    ]
